// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vzuloquszlnrosrcdxeh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ6dWxvcXVzemxucm9zcmNkeGVoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5MjYxMTksImV4cCI6MjA2NTUwMjExOX0.S-kgo18aBf8zntOYi_AR8OJmjXbKfnhn8guNpqX6wp0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);